# Generated by Django 5.0.7 on 2024-08-01 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManasuApp', '0002_remove_userprofile_additional_info_userprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='mental_health_problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='ManasuApp.mentalhealthproblem'),
        ),
    ]
