# Generated by Django 5.0.7 on 2024-08-02 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManasuApp', '0004_mentalhealthsummary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='value',
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MC', 'Multiple Choice'), ('OE', 'Open Ended')], default='MC', max_length=2),
        ),
    ]
