# Generated by Django 5.0.7 on 2024-08-02 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManasuApp', '0005_remove_option_value_question_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='open_ended_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userresponse',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ManasuApp.option'),
        ),
    ]
