# Generated by Django 5.0.7 on 2024-08-02 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ManasuApp', '0006_userresponse_open_ended_response_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
    ]
