# Generated by Django 5.0.7 on 2024-08-03 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManasuApp', '0009_remove_mentalhealthsummary_recommendations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentalhealthsummary',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
