# Generated by Django 5.0.7 on 2024-08-03 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManasuApp', '0010_mentalhealthsummary_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='suggested_by_ai',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='goal',
            name='suggested_by_ai',
            field=models.BooleanField(default=False),
        ),
    ]
