# Generated by Django 5.0.7 on 2024-08-03 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ManasuApp', '0012_userpatternandtrigger'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
