# Generated by Django 5.0.7 on 2024-08-03 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ManasuApp', '0014_chatsession_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='session',
        ),
        migrations.DeleteModel(
            name='ChatSession',
        ),
    ]
