# Generated by Django 5.0.7 on 2024-08-04 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ManasuApp', '0015_remove_chat_session_delete_chatsession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
    ]
